In [1]:
import dlc_bci as bci
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
import os
import numpy as np
import torch

train_̇input, train_̇target = bci.load(root='./data', train=True, store_local=True)

#print(str(type(train_̇input)), train_̇input.size())
#print(str(type(train_̇target)), train_̇target.size())
test_̇input, test_̇target = bci.load(root='./data', train=False, store_local=True)
#print(str(type(test_̇input)), test_̇input.size())
#print(str(type(test_̇target)), test_̇target.size())

In [2]:
test_ex = train_̇input[0].numpy()
print(test_ex)
print(np.shape(test_ex))

[[ 41.8  44.8  47.1 ...  69.8  72.6  76.1]
 [-10.3  -5.9  -3.3 ...  12.6  24.   26.5]
 [ 38.1  25.2  46.  ...  45.1  74.1  64.8]
 ...
 [  7.9  11.2  14.3 ...  32.7  43.4  45.5]
 [ 19.2  33.6  33.8 ...  46.7  53.7  43.4]
 [ -0.4  12.7  12.  ...  30.7  40.6  33.1]]
(28, 50)


In [ ]:
def generate_figures(number, folder):
    if not os.path.exists(folder): os.mkdir(folder)
    for i in range(0, number):
        test_ex = train_̇input[i].numpy()
        target = train_̇target[i]
        fig = plt.figure(figsize=(40, 40))
        ax = fig.add_subplot(111, projection="3d")
        x_axes = np.arange(np.shape(test_ex)[0])
        y_axes = np.arange(np.shape(test_ex)[1])
        X, Y = np.meshgrid(y_axes, x_axes)
        ax.plot_surface(X, Y, test_ex, cmap=cm.coolwarm)
        s = str('%i_test_%i.png' %(int(target), i))
        path = os.path.join(folder, s)
        plt.savefig(fname=path)

generate_figures(20, 'figs')



